name: arc_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=5_kmp_llvm
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.33=py37h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libblas=3.9.0=21_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=21_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=21_linux64_mkl
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=20.1.8=h4922eb0_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.5.2=py37hc347a89_0
  - mkl=2024.0.0=ha957f24_49657
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.6=py37h976b520_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycocotools=2.0.4=py37hb1e94ed_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.13.1=py3.7_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - requests=2.28.1=py37h06a4308_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.5.0=h924138e_1
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.13.1=py37_cu117
  - torchvision=0.14.1=py37_cu117
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - unicodedata2=14.0.0=py37h540881e_1
  - urllib3=1.26.14=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - easydict==1.13
      - filelock==3.12.2
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - huggingface-hub==0.16.4
      - importlib-metadata==6.7.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - munkres==1.1.4
      - natsort==8.4.0
      - networkx==2.6.3
      - opencv-python==4.12.0.88
      - packaging==24.0
      - protobuf==4.24.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - safetensors==0.4.3
      - scipy==1.1.0
      - tensorboardx==2.6.2.2
      - terminaltables==3.1.10
      - timm==0.9.12
      - tornado==6.2
      - tqdm==4.67.1
      - visdom==0.2.4
      - websocket-client==1.6.1
      - zipp==3.15.0
prefix: /home/vic03/anaconda3/envs/arc_env
