DATASET:
  TRAIN:
    TYPE: 'H36mMpii'
    SET_LIST:
      - ROOT: './data/h36m/'
        TRAIN_SET: 'Sample_trainmin_train_Human36M'
      - ROOT: './data/mpii/'
        TRAIN_SET: 'annot_mpii'
  VAL:
    TYPE: 'H36mMpii'
    TEST_SET: 'Sample_64_test_Human36M'

DATA_PRESET:
  TYPE: 'simple_3d'
  PROTOCOL: 2
  SIGMA: 2
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.3
  COLOR_FACTOR: 0.2
  OUT_3D: True
  PROB_HALF_BODY: -1
  OCCLUSION: True
  NUM_JOINTS_HALF_BODY: 8

  NUM_JOINTS: 18
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64

MODEL:
  TYPE: 'ConvNextPose'
  PRETRAINED: ''
  TRY_LOAD: ''

  depth_dim: 32
  embedding_size: 768  
  head_channels: 128
  drop_rate: 0.1      
  quant_flag: false
  convnext_type: 50

LOSS:
  TYPE: 'MSELoss' 

TEST:
  HEATMAP2COORD: 'heatmap'
  FLIP_TEST: true
  FLIP_SHIFT: true

TRAIN:
  WORLD_SIZE: 2
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 1
  OPTIMIZER: 'adam'
  GRAD_CLIP:
    MAX_NORM: 35
    NORM_TYPE: 2
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120